version: '3.3'

services:

  #Mysql
  db:
    image: mariadb:10.6
    container_name: system-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose: 
      - 3306
    volumes:
      - ./mysql/:/docker-entrypoint-initdb.d  
      - ./mysql/data:/var/lib/mysql           
    restart: always  

  #phpMyAdmin     
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1
    container_name: system-phpmyadmin
    ports:
      - "8081:80"    
    depends_on:
      - db
    links:
      - db
    restart: always
    
  #Web Service
  web:
    build: 
      context: ./web/
      dockerfile: Dockerfile
    depends_on: 
      - db
    container_name: system-web-server
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8080:80" 
    volumes:
      - type: bind
        source: ./web/src/
        target: /var/www/html/
    restart: always
    links:
      - db

